#!/bin/sh

make_writable() {
	local dir size
	dir="${1%/}"
        size=$2
        [ -n "$size" ] && size=",size=$size"

	echo -n "Binding $dir to ramdisk:"
	echo -n " mount" && mount -n -t tmpfs -o mode=755${size+$size} none /mnt &&
	echo -n " rsync" && rsync --numeric-ids -arz $dir/ /mnt/ &&
	echo -n " bind" && mount -n --bind /mnt $dir &&
	echo " umount" && umount /mnt 2>/dev/null
}
